Imported opensc-0.12.0
Summary: Imported opensc-0.12.0
Keywords:

Imported opensc-0.12.0
into Git repository

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,4 +1,3 @@
-AUTOMAKE_OPTIONS = foreign 1.10
 ACLOCAL_AMFLAGS = -I m4
 
 MAINTAINERCLEANFILES = \
@@ -22,6 +21,18 @@ dist_noinst_DATA = README \
 	solaris/opensc.conf-dist solaris/pkginfo.in solaris/proto
 dist_doc_DATA = NEWS
 
-# Allow detection of packaged tarball
-dist-hook:
-	echo > "$(distdir)/packaged"
+Generate-ChangeLog:
+	rm -f ChangeLog.tmp "$(srcdir)/ChangeLog"
+	test -n "$(SVN)" -a -n "$(XSLTPROC)"
+	if test -d "$(top_srcdir)/.svn"; then \
+		$(SVN) --verbose --xml log "$(top_srcdir)" | \
+			$(XSLTPROC) --nonet --stringparam linelen 75 \
+			--stringparam groupbyday no \
+			--stringparam include-rev no \
+			"$(top_srcdir)/doc/svn2cl.xsl" - > ChangeLog.tmp; \
+	else \
+		echo "Warning: Unable to generate ChangeLog from none svn checkout" >&2; \
+		echo > ChangeLog.tmp; \
+	fi
+	mv ChangeLog.tmp "$(srcdir)/ChangeLog"
+	( cd "$(srcdir)" && autoreconf -ivf )
